# åŸºæœ¬è¨­å®š
baseURL = 'https://tarrragon.github.io/blog/'
theme = 'hugo-bearcub'
copyright = 'Tarragon (CC BY 4.0)'
defaultContentLanguage = 'zh-tw'

# ç”¢ç”Ÿ robots.txt ä»¥åˆ©æ–¼ SEO
enableRobotsTXT = true

# æ‘˜è¦è¨­å®š
summaryLength = 200  # æ‘˜è¦å­—æ•¸é™åˆ¶

# è¨­å®šèªæ³•é«˜äº®
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# å¤šèªè¨€æ¨¡å¼è¨­å®š
[languages]
  [languages.zh-tw]
    title = 'Tarragon'
    languageName = 'zh-TW ğŸ‡¹ğŸ‡¼'
    LanguageCode = 'zh-TW'
    contentDir = 'content'
    [languages.zh-tw.params]
      madeWith = 'ä½¿ç”¨ [Bear Cub](https://github.com/clente/hugo-bearcub) è£½ä½œ'

# å°èˆªé¸å–®è¨­å®š
[menu]
  
  [[menu.main]]
    name = "æ–‡ç« "
    url = "/posts/"
    weight = 5

  [[menu.main]]
    name = "æ¨™ç±¤"
    url = "/tags/"
    weight = 10
  
 

[params]
  # ç¶²ç«™æè¿°
  description = 'ä¸€å€‹éƒ¨è½æ ¼'

  # ç¶²ç«™æ¨™é¡Œ
  title = 'Tarragon'

  # æ—¥æœŸæ ¼å¼
  dateFormat = '2006-01-02'

  # ä¸»é¡Œæ¨£å¼ (original æˆ– herman)
  themeStyle = 'herman'

  # è‡ªå‹•ç”¢ç”Ÿç¤¾ç¾¤åª’é«”å¡ç‰‡
  generateSocialCard = true

  # ä½œè€…è³‡è¨Š
  [params.author]
    name = 'tarragon'
    email = 'tarragonstop@gmail.com'

#æ°¸ä¹…é€£çµ  
[permalinks]
  posts = "/posts/:slug/"
  work-log = "/work-log/:slug/"
  work-log = "/record/:slug/"